export const queryKeys = {
  GET_DETAIL_MATCH: "GET_DETAIL_MATCH",
  GET_LIST_MATCH: "GET_LIST_MATCH",
  GET_MATCH_OVERVIEW: "GET_MATCH_OVERVIEW",
  GET_MATCH_LINEUPS: "GET_MATCH_LINEUPS",
  GET_MATCH_EVENTS: "GET_MATCH_EVENTS",
};
